### ISSUE TITLE
changes to docker-compose.yml to work with 1.17.1

### ISSUE THREAD

**Issue by anewton1998** [dessalines/lemmy#166]
Installing on Ubuntu, it comes with docker-compose 1.17.1.

I had to change my docker-compose.yml file to work with this version. It is below:

```
version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rrr
      POSTGRES_PASSWORD: rrr
      POSTGRES_DB: rrr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rrr"]
      interval: 5s
      timeout: 5s
      retries: 20
  lemmy:
    image: dessalines/lemmy:latest
    ports:
      - "8536:8536"
    environment:
      LEMMY_FRONT_END_DIR: /app/dist
      DATABASE_URL: postgres://rrr:rrr@db:5432/rrr
      JWT_SECRET: emdashg
      HOSTNAME: rrr
    restart: always
    depends_on: 
      - db 
```
