### ISSUE TITLE
Automatically configure mailserver with ansible/docker-compose Deployment

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#473]
```
  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=${PEERTUBE_WEBSERVER_HOSTNAME}
    restart: "always"
```
