### ISSUE TITLE
Could not communicate with the postgres container

### ISSUE THREAD

**Issue by remyd1** [dessalines/lemmy#540]
Hi,

I am not able to launch the lemmy docker-compose. Indeed, I have the following error while trying to launch the docker-compose:

```bash
[2020-02-17T13:03:28Z ERROR r2d2] could not translate host name "lemmy_db" to address: Try again
```
In lemmy.hjson, I have:

```
...
    # host where postgres is running
    host: "lemmy_db"
...
```

And, in the docker-compose file:
```
version: '3.3'

services:
  lemmy_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD="secret"
      - POSTGRES_DB=lemmy
    volumes:
      - lemmy_db:/var/lib/postgresql/data
    restart: always
  lemmy:
    image: dessalines/lemmy:v0.6.18
    ports:
      - "127.0.0.1:8536:8536"
    restart: always
    volumes:
      - ./lemmy.hjson:/config/config.hjson:ro
    depends_on:
      - lemmy_db
  lemmy_pictshare:
    image: shtripok/pictshare:latest
    ports:
      - "127.0.0.1:8537:80"
    volumes:
      - lemmy_pictshare:/usr/share/nginx/html/data
    restart: always
    depends_on:
      - lemmy_db

volumes:
  lemmy_db:
  lemmy_pictshare:
```

My docker-compose version:

```
docker-compose version 1.25.3, build d4d1b42b
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

Best regards,
